### ISSUE TITLE
can i training my own dataset？

### ISSUE THREAD

**Issue by overing1314** [ZivFung/zedboard_cnn#2]
我想问下 ，我能自己训练模型放在这个项目吗？你是如如让他识别号码的？

**Comment by ZivFung** [comment]
没有做训练的部分，模型是固定，可以调参数，要改模型就要改代码。模型参考LeNet，比LeNet还简单，只能识别单个数字是多少。你可以看看我的代码，几层卷积，几层池化，激活函数什么的。
