### ISSUE TITLE
Which 1 is 

### ISSUE THREAD

**Issue by overing1314** [ZivFung/zedboard_cnn#3]
请问一下，这个是不是接7晶管的port呢 ？

set_property -dict {PACKAGE_PIN R6 IOSTANDARD LVCMOS33} [get_ports {seg[0]}]
set_property -dict {PACKAGE_PIN T6 IOSTANDARD LVCMOS33} [get_ports {seg[1]}]
set_property -dict {PACKAGE_PIN AB7 IOSTANDARD LVCMOS33} [get_ports {seg[2]}]
set_property -dict {PACKAGE_PIN AB6 IOSTANDARD LVCMOS33} [get_ports {seg[3]}]
set_property -dict {PACKAGE_PIN Y4 IOSTANDARD LVCMOS33} [get_ports {seg[4]}]
set_property -dict {PACKAGE_PIN U4 IOSTANDARD LVCMOS33} [get_ports {seg[5]}]
set_property -dict {PACKAGE_PIN T4 IOSTANDARD LVCMOS33} [get_ports {seg[6]}]
set_property -dict {PACKAGE_PIN AA4 IOSTANDARD LVCMOS33} [get_ports {seg[7]}]

![image](https://user-images.githubusercontent.com/36887809/83369609-86a9af00-a3ef-11ea-9517-8bf8947f9c01.png)

**Comment by ZivFung** [comment]
嗯，是接数码管的

**Comment by overing1314** [comment]
> 嗯，是接数码管的

在pinset里 你是设置为 led[0], led[1] ...
根据上面图的脚，
请问 a 是不是 对应 led[0], b 对应 led[1] 。。。以此类推？？

**Comment by ZivFung** [comment]
led是led，数码管是数码管。至于顺序我现在也记不得了，应该是seg[0]-a seg[1]-b……吧。。。。

**Comment by overing1314** [comment]
你有试过ov7670拍出来的画面像爆光一样，看不到东西，好像只有光的画面一样。。。

**Comment by overing1314** [comment]
还有大大，请问你是用什么版本的vivado ? 我是用·vivado 2018.2 版本。。。

**Comment by overing1314** [comment]
> led是led，数码管是数码管。至于顺序我现在也记不得了，应该是seg[0]-a seg[1]-b……吧。。。。
那么数码管的dp是哪一个port呢？

**Comment by ZivFung** [comment]
没用小数点，只识别0-9的数字，所以应该没搞dp

**Comment by overing1314** [comment]
> 没用小数点，只识别0-9的数字，所以应该没搞dp

但是你的pinset里 从 seg[0] 到 seg[7] 有8 个， 7晶 数码管 只有7 个 脚， 多了一个 是什么？

**Comment by overing1314** [comment]
帮帮忙 大大~

**Comment by ZivFung** [comment]
你看一眼代码就好了，case从上到下是0~9，所以应该最高位到最低位是dp，g，f.......a

**Comment by overing1314** [comment]
> 你看一眼代码就好了，case从上到下是0~9，所以应该最高位到最低位是dp，g，f.......a
 我刚刚看了，已经明白了，谢谢你啊~

**Comment by overing1314** [comment]
> 你看一眼代码就好了，case从上到下是0~9，所以应该最高位到最低位是dp，g，f.......a

我刚刚看了，已经明白了，谢谢你啊
