### ISSUE TITLE
谢谢Jiaxiang Feng大大这半年的帮助~

### ISSUE THREAD

**Issue by overing1314** [ZivFung/zedboard_cnn#4]
谢谢大大你每次的帮忙。从1月开始，没次遇到难题都询问你，你都很有耐心的帮我解答。我其实是FPGA新人，至今使用FPGA不到6个月，就有极大的挑战要我实现CNN实时侦测的在FPGA上。我依然还是很懵懂，不是说什么程序高手。但是我是很有心想学习FPGA的。你的帮助激起了让我想继续学FPGA的冲动。虽然你说过这个并不是什么大型project，但是对我而言，我从中学到了很多。在我实现这代码的过程中，我透过这些代码吸取到大大制作的经验以及流程，让我明白在FPGA要实现CNN的概念以及步骤，这真是很好的实战体验。感恩有你~

**Comment by ZivFung** [comment]
没事没事，我这个东西确实写的也不太好，当时也是应付差事用的，我也只是搞点FPGA，机器学习啥的都是二流子 哈哈。FPGA的开发确实很有意思，如果你感兴趣的话也希望你能坚持继续学下去，加油！
